const { Router } = require("express");

const cityRoutes = require("./city-service/routes");
const localityRoutes = require("./locality-service/routes");
const buildingRoutes = require("./building-service/routes");
const flatRoutes = require("./flat-service/routes");
const userRoutes = require("./user-service/routes");
const visitorRoutes = require("./visitor-service/routes");
const guardRoutes = require("./guard-service/routes");
const uploadRoutes = require("./upload-service/routes");
const visitingRoutes = require("./visiting-service/routes");
const noticeRoutes = require("./notice-service/routes");
const helplineNumberRoutes = require("./helpline-service/routes");
const userNotificationRoutes = require("./userNotification-service/routes");
const familyMemberRoutes = require("./familyMember-service/routes");
const floorRoutes = require("./floor-service/routes");
const postRoutes = require("./post-service/routes");
const likeRoutes = require("./like-service/routes");
const commentRoutes = require("./comment-service/routes");
const shareRoutes = require("./share-service/routes");
const marketPlaceRoutes = require("./marketPlace-service/routes");
const savedItemRoutes = require("./savedItem-service/routes");
const feedRoutes = require("./feed-service/routes");
const maintenanceRequestRoutes = require("./maintenanceRequest-service/routes");
const chargeRoutes = require("./charge-service/routes");
const adminRoutes = require("./admin-service/routes");
const masterUserRoutes = require("./masterUser-service/routes");
const flatContractRoutes = require("./flatContract-service/routes");
const staffRoutes = require("./staff-service/routes");
const maintenanceCatalogueRoutes = require("./maintenanceCatalogue-service/routes");
const dashboardRoutes = require("./dashboard-service/routes");
const propertyRoutes = require("./property-service/routes");
const timeSlotRoutes = require("./timeslot-service/routes");
const imageRoutes = require("./image-service/routes");
const assetRoutes = require("./asset-service/routes");
const ppmRoutes = require("./preventativeMaintenace-service/routes");
const crmRoutes = require("./crmLog-service/routes");
const inventoryRoutes = require("./inventory-service/routes");
const adminNotificationRoutes = require("./adminNotification-service/routes");
const owner = require("./owner-service/routes");
const subFlats = require("./subFlat-service/routes");
const ownerNotificationRoutes = require("./ownerNotification-service/routes");
const leaseRoutes = require("./lease-service/routes");
const tokenRoutes = require("./token-service/routes");
const leaseReminderRoutes = require("./leaseReminder-service/routes");
const amenityRoutes = require("../src/amenity-service/routes/index");
const invoiceRoutes = require("../src/invoice-service/routes");
const tagRoutes = require("../src/tags-service/routes");
const clientRoutes = require("../src/client-service/routes")

const appRoutes = Router();

appRoutes.use("/cities", cityRoutes);
appRoutes.use("/localities", localityRoutes);
appRoutes.use("/buildings", buildingRoutes);
appRoutes.use("/flats", flatRoutes);
appRoutes.use("/users", userRoutes);
appRoutes.use("/visitors", visitorRoutes);
appRoutes.use("/guards", guardRoutes);
appRoutes.use("/files", uploadRoutes);
appRoutes.use("/visitings", visitingRoutes);
appRoutes.use("/notices", noticeRoutes);
appRoutes.use("/helplines", helplineNumberRoutes);
appRoutes.use("/notifications", userNotificationRoutes);
appRoutes.use("/family-members", familyMemberRoutes);
appRoutes.use("/floors", floorRoutes);
appRoutes.use("/posts", postRoutes);
appRoutes.use("/likes", likeRoutes);
appRoutes.use("/comments", commentRoutes);
appRoutes.use("/shares", shareRoutes);
appRoutes.use("/marketplace", marketPlaceRoutes);
appRoutes.use("/feeds", feedRoutes);
appRoutes.use("/saved-items", savedItemRoutes);
appRoutes.use("/maintenances", maintenanceRequestRoutes);
appRoutes.use("/charges", chargeRoutes);
appRoutes.use("/admins", adminRoutes);
appRoutes.use("/master-users", masterUserRoutes);
appRoutes.use("/flat-contracts", flatContractRoutes);
appRoutes.use("/staffs", staffRoutes);
appRoutes.use("/maintenance-catalogues", maintenanceCatalogueRoutes);
appRoutes.use("/dashboard", dashboardRoutes);
appRoutes.use("/properties", propertyRoutes);
appRoutes.use("/timeslots", timeSlotRoutes);
appRoutes.use("/images", imageRoutes);
appRoutes.use("/assets", assetRoutes);
appRoutes.use("/ppm", ppmRoutes);
appRoutes.use("/crm", crmRoutes);
appRoutes.use("/inventories", inventoryRoutes);
appRoutes.use("/admin-notifications", adminNotificationRoutes);
appRoutes.use("/sub-flats", subFlats);
appRoutes.use("/owners", owner);
appRoutes.use("/owner-notifications", ownerNotificationRoutes);
appRoutes.use("/leases", leaseRoutes);
appRoutes.use("/tokens", tokenRoutes);
appRoutes.use("/lease-reminders", leaseReminderRoutes);
appRoutes.use("/amenities", amenityRoutes);
appRoutes.use("/invoices", invoiceRoutes);
appRoutes.use("/tags", tagRoutes);
appRoutes.use("/clients", clientRoutes);
// appRoutes.use('/super-admin', superAdminRoutes);


module.exports = { appRoutes };
